[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn backend.wsgi:application"
healthCheckPath = "/"
restartPolicyType = "on_failure"

[build.nixpacks]
packages = ["python311", "gcc", "postgresql"]
setupKeys = ["PYTHON_VERSION=3.11.7"]
